# Generated by Django 5.2.7 on 2025-10-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modul', models.CharField(max_length=100)),
                ('lMavzu', models.CharField(max_length=150)),
                ('Savol_ID', models.IntegerField(unique=True)),
                ('Savol_Matni', models.TextField()),
                ('Variant_A', models.CharField(max_length=255)),
                ('Variant_B', models.CharField(max_length=255)),
                ('Variant_C', models.CharField(max_length=255)),
                ('Variant_D', models.CharField(max_length=255)),
                ('To_g_ri_Javob', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(max_length=100)),
                ('mavzu', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.user')),
            ],
        ),
    ]
