# Generated by Django 5.2.7 on 2025-10-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Savol_ID',
            field=models.IntegerField(),
        ),
    ]
