# Generated by Django 5.2.7 on 2025-10-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_savol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='mavzu',
        ),
    ]
